import argparse
import os
import re
import sys

import mutation_stats

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
README_PATH = os.path.join(ROOT, "README.md")
OUTPUT_PATH = os.path.join(ROOT, "VERIFICATION.md")

GROUPS = [
    ("CAS and the parsing engine", (
        "src/engine/cas.zig", "src/engine/symbol.zig", "src/engine/boundedness.zig",
        "src/engine/checks.zig", "src/engine/functions.zig", "src/engine/ref.zig",
        "src/engine/loader.zig", "src/engine/coverage.zig", "src/engine/regex.zig",
        "src/engine/test_util.zig", "tests/lang/cases.zig", "tests/zig_source.zig",
        "src/engine/symmetry.zig", "src/engine/removal.zig",
    )),
    ("Sandbox and the test/typecheck gate", (
        "src/platform/sandbox.zig", "src/platform/runner.zig", "src/platform/lockdown.zig",
        "src/platform/shadow.zig", "src/platform/batch.zig",
    )),
    ("Disk, repository boundary and atomic commit", (
        "src/platform/disk.zig", "src/platform/repo.zig", "src/platform/gate.zig",
        "src/platform/journal.zig", "src/platform/commit_record.zig", "src/platform/create.zig",
        "src/platform/batch_plan.zig",
    )),
    ("Rules and the q: query engine", (
        "src/platform/rules.zig", "src/platform/where.zig", "src/engine/query.zig",
        "src/protocol/rule_command.zig", "src/protocol/policy.zig",
    )),
    ("Scan", (
        "src/platform/scan.zig", "src/protocol/scan_command.zig",
    )),
    ("Memory and the decision ledger", (
        "src/platform/memory.zig",
    )),
    ("Mutation testing tool itself", (
        "tools/mutate/core.zig", "tools/mutate/changes.zig", "tools/mutate/schema.zig",
        "tools/test_runner.zig",
    )),
]

OTHER_GROUP = "Protocol wiring and everything else"

load_mutations = mutation_stats.load_mutations
classify = mutation_stats.classify


def group_for(file_path):
    for name, files in GROUPS:
        if file_path in files:
            return name
    return OTHER_GROUP


def escape_cell(text):
    return text.replace("|", "\\|").replace("`", "'")


def truncate(text, limit=64):
    text = escape_cell(text.replace("\n", " ").strip())
    if len(text) <= limit:
        return text
    return text[: limit - 1] + "..."


def count_zig_tests():
    total = 0
    for base in ("src", "tests", "tools"):
        for dirpath, _, filenames in os.walk(os.path.join(ROOT, base)):
            for name in filenames:
                if not name.endswith(".zig"):
                    continue
                path = os.path.join(dirpath, name)
                with open(path, encoding="utf-8", errors="surrogateescape") as f:
                    for line in f:
                        if line.startswith("test \""):
                            total += 1
    return total


def count_redteam_tests():
    counts = {}
    for name in os.listdir(os.path.join(ROOT, "tests")):
        if name.startswith("redteam_") and name.endswith(".zig"):
            path = os.path.join(ROOT, "tests", name)
            with open(path, encoding="utf-8") as f:
                n = sum(1 for line in f if line.startswith("test \""))
            counts[name] = n
    return counts


def security_findings():
    with open(README_PATH, encoding="utf-8") as f:
        text = f.read()
    section = text.split("## Security history", 1)[1].split("## Limits", 1)[0]
    return re.findall(r"\*\*(F\d[^*]*|Repository ledger[^*]*)\*\*", section)


def render(mutations):
    total = len(mutations)
    by_status = {}
    for m in mutations:
        by_status.setdefault(classify(m), []).append(m)
    zig_tests = count_zig_tests()
    redteam = count_redteam_tests()
    findings = security_findings()

    lines = []
    lines.append("# How Emetgate Is Verified")
    lines.append("")
    lines.append(
        "Generated by `tools/verification_page.py` from `tests/mutations.json` and "
        "`README.md`. Do not edit by hand; `python tools/verification_page.py` "
        "regenerates it, and `python tools/verification_page.py --check` fails if this "
        "file is out of date."
    )
    lines.append("")
    lines.append(
        "The claim this page backs: the kernel's guards are not just written, they are "
        "each covered by a test that fails when the guard is weakened one way, and "
        "checked as far as the mutation tool could push it when the guard survives "
        "unchanged. This follows the framing in Anderson's reference monitor: complete "
        "mediation is `emetgate lockdown`, tamper-resistance is the sandbox and the "
        "ledger's trust rules, verifiability is this page."
    )
    lines.append("")
    lines.append("## Numbers")
    lines.append("")
    lines.append(f"- `test \"...\"` blocks in `src/`, `tests/`, `tools/`: **{zig_tests}**")
    lines.append(f"- Mutations declared in `tests/mutations.json`: **{total}**")
    known_statuses = (
        "killed", "equivalent", "defense in depth", "open", "control",
        "compile-error control", "not caught by a test, documented as unbounded cost",
        "verified end-to-end, not by the mutation harness",
    )
    for status in known_statuses:
        if status in by_status:
            lines.append(f"  - {status}: **{len(by_status[status])}**")
    unclassified = by_status.get("survives (unclassified)", [])
    if unclassified:
        lines.append(f"  - survives, not yet classified: **{len(unclassified)}** ({', '.join(m['id'] for m in unclassified)})")
    lines.append(f"- Red-team suites: **{len(redteam)}** files, **{sum(redteam.values())}** tests total")
    for name, n in sorted(redteam.items()):
        lines.append(f"  - `tests/{name}`: {n}")
    lines.append(f"- Security findings recorded in README's Security History: **{len(findings)}**")
    lines.append("")
    lines.append("## Reproducing this")
    lines.append("")
    lines.append("```")
    lines.append("zig build test")
    lines.append("zig build mutate-tool")
    lines.append("zig-out/bin/emetgate-mutate.exe --jobs=4")
    lines.append("python tools/verification_page.py --check")
    lines.append("```")
    lines.append("")
    lines.append(
        "`tools/accept.ps1 <ref>` runs the same steps (scoped to mutations on lines "
        "changed since `<ref>`) plus this file's staleness check, and is what CI and "
        "every development session run before a change is reported done."
    )
    lines.append("")
    lines.append("## Invariants by area")
    lines.append("")
    for name, _files in GROUPS + [(OTHER_GROUP, ())]:
        rows = [m for m in mutations if group_for(m["file"]) == name]
        if not rows:
            continue
        lines.append(f"### {name}")
        lines.append("")
        lines.append(f"{len(rows)} mutation(s).")
        lines.append("")
        lines.append("| Mutant | File | Change | Proved by | Status |")
        lines.append("|---|---|---|---|---|")
        for m in rows:
            change = f"`{truncate(m['from'])}` -> `{truncate(m['to'])}`"
            kills = m.get("kills") or []
            proved_by = "; ".join(truncate(k, 80) for k in kills) if kills else (m.get("note") or "")
            status = classify(m)
            lines.append(f"| `{m['id']}` | `{m['file']}` | {change} | {truncate(proved_by, 90)} | {status} |")
        lines.append("")
    lines.append("## What this system does not prove")
    lines.append("")
    lines.append(
        "- **Semantic correctness.** A change that parses, stays in its structural "
        "bounds and passes the given tests can still do the wrong thing; whether it "
        "does is undecidable in general (Rice's theorem) and this kernel does not try "
        "to decide it. It replaces search-and-replace editing with a checked one, not "
        "a proof of intent."
    )
    lines.append(
        "- **The test oracle's own strength.** For an unbounded (test-gated) change, "
        "the verdict is only as good as the test command the user supplied; a weak or "
        "missing test lets a wrong change through the same way it would without this "
        "kernel."
    )
    lines.append(
        "- **Anything outside the gate.** These guarantees hold for edits that go "
        "through `try`/`try_batch`; a tool or a human editing the file directly "
        "bypasses all of it, which is why `lockdown` exists and is a separate claim "
        "from the ones on this page."
    )
    lines.append(
        "- **Non-Windows platforms.** The sandbox depends on Windows Job Objects and "
        "restricted tokens; none of the sandbox mutation or red-team results say "
        "anything about another OS."
    )
    lines.append(
        "- **A mutant proven equivalent or open stays open.** \"Equivalent\" here means "
        "a specific argument was made for why no test can distinguish the mutant from "
        "the original, not a machine-checked proof; \"open\" means no killing input was "
        "found yet, not that none exists."
    )
    lines.append("")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    mutations = load_mutations()
    content = render(mutations)

    if args.check:
        if not os.path.exists(OUTPUT_PATH):
            print("VERIFICATION.md is missing; run tools/verification_page.py")
            sys.exit(1)
        with open(OUTPUT_PATH, encoding="utf-8") as f:
            current = f.read()
        if current != content:
            print("VERIFICATION.md is stale; run: python tools/verification_page.py")
            sys.exit(1)
        print("VERIFICATION.md is up to date")
        return

    with open(OUTPUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
